sentence_test_parte_1 = '''La chiesa della confraternita viene eretta nel 1538, segno dell’affermazione di un notabilato che controlla la vita economica e sociale della comunità e sviluppatosi tra la metà del Quattrocento e la fine del Cinquecento, a seguito dell’incremento dei traffici commerciali. La rete economica favorisce anche la circolazione di artisti.
                    I confratelli di Santa Croce commissionano (1658 - 1660) un ciclo di dodici tele a Lorenzo Gastaldi.
                    La scelta del pittore, che in quel momento si trova a Monaco, e realizza molte opere per le valli del Nizzardo e il basso cuneese, si spiega con interessi economici della comunità e alle frequentazioni liguri-nizzarde della popolazione locale.  Durante il Seicento gli entracquesi vendono ovini e bovini ai macelli di Grasse, Nizza e Genova.
                    Sovente alcuni abitanti si recavano per affari a Tenda, raggiunta attraverso i colli delle Finestre e del Sabbione. A partire dagli anni Settanta del Seicento è potenziata l’attività mercantile, a cui corrisponde il tentativo di rilanciare l’antica strada del colle delle Finestre, che in seguito al potenziamento della strada del colle di Tenda aveva perso la sua importanza.
                    I rapporti di Entracque con la valle della Vesubie, attraverso il colle delle Finestre, sulla strada di Nizza, determinarono almeno un altro episodio di committenza: il “mastro da bosco” (falegname) Giacomo Rosso di Lantosca realizza nel 1684 un armadio per la parrocchiale di Sant’Antonino.'''

sentence_test_parte_2 = '''Si tratta di dodici teleri raffiguranti episodi della vita di Cristo e della Vergine. Una scelta che risponde ai dogmi affermati dalla Chiesa cattolica della Controriforma, l’Immacolata Concezione della Vergine, la Trinità, il riscatto del genere umano attraverso il Sacrificio di Cristo. A questo si aggiungono i riferimenti alle pratiche liturgiche svolte dai confratelli durante il Giovedì Santo, rievocate nell’Ultima Cena e soprattutto nella Lavanda dei piedi.
Il modello decorativo di riferimento è quello della Confraternita di Santa Croce a Cuneo, dove nel 1626 sono allestite le tele con i Miracoli della Vera Croce dipinti nel 1626 da Giulio e Giovanni Battista Bruno (che a loro volta rimandano ai modelli decorativi di primo Seicento delle Casacce (oratori), genovesi.
'''

sentence_test_parte_3 = '''Lorenzo Gastaldi è un pittore originario di Triora (1625-1690); dal 1651 si trasferisce a Monaco dove si ritaglia uno spazio a corte, per poi passare a Nizza e ritornare a Triora nel 1676. Molte sono le opere da lui realizzate, destinate alle valli del Nizzardo e del basso Cuneese. 
Le sue opere sono presenti a La Brigue (per la parrocchiale, Immacolata con i santi Sebastiano, Giuseppe, Rocco e Carlo Borromeo), a Peillon (per la parrocchiale, Madonna del Rosario), a Contes in Val Paillon (per la parrocchiale, Pentecoste); a Triora (Natività del Battista per l’Oratorio di San Giovanni Battista); in valle Stura a Bersezio (per la parrocchiale, Madonna con il Bambino e santi; Sacra Famiglia); Pontebernardo (per la parrocchiale, Madonna con il Bambino, Santi e la Sindone; Moiola; Vernante (per la parrocchiale, la Sindone, 1671; Roccavione (per la cappella dei Santi Rocco e Biagio, 1676; per la parrocchiale uno stendardo per la Compagnia del Rosario, 1678); Demonte (parrocchiale, Madonna con il Bambino e i santi Marco evangelista, Chiara, Grato e Barbara); nella valle della Tinèe, a Isola (per la parrocchiale, Incoronazione della Vergine e i santi Bernardo e Lorenzo)
'''

articolo2_parte_1 = '''La necessità dei Savoia di garantirsi un percorso alternativo alla strada del Col di Tenda che colleghi le loro terre cisalpine con Nizza, in modo da evitare gli esosi pedaggi imposti dai signori di Tenda alle merci che transitano nei territori da loro controllati, è uno degli elementi determinanti per lo sviluppo economico che caratterizza la comunità della Valle Gesso a partire dalla seconda metà del secolo XV. L’acquisizione della Contea di Tenda da parte dei Savoia nel 1579 determina la scelta di privilegiare la strada che l’attraversa per il trasporto delle merci.'''

articolo2_parte_2 = '''Gli itinerari che si diramano verso la Francia sono due: 
1.	Il primo da Borgo San Dalmazzo attraversava la valle Vermenagna e valicava il colle di Tenda in direzione di Nizza. Percorreva la valle Roya fino a Breglio e per il colle del Brouis raggiungeva Sospello; da qui valicando il Braus, scendeva a L’Escarène??? e sbucava a Nizza.
2.	Il secondo, parallelo, imboccava la valle Gesso e salendo ad Entracque valicava il colle delle Finestre e si immetteva nella val Vésubie, attraversava St. Martin e Lantosca. Da qui in su si snodavano due tragitti per Nizza: uno passante per Lévens e l’altro per Utelle. [AGGANCIO: Santuario di Madonna di Finestra di culto e di ospitalità posto su uno dei tanti sentieri di raccordo del cammino verso Santiago de Compostela]
La difficoltà di percorso delle due strade era equivalente: la percorrenza delle distanze poteva essere effettuata in 8 ore da ambe le parti.
La strada della Val Roya era la più battuta, nonostante il peso dei pedaggi: il passaggio del col di Tenda doveva essere più vantaggioso per la minore altitudine e la più facile percorribilità nei mesi invernali.
'''

xx = "I confratelli di Santa Croce commissionano (1658 - 1660) un ciclo di dodici tele a Lorenzo Gastaldi."

test1 = "Un gruppo di affreschi, da datare intorno alla seconda metà del Quattrocento,  appaiono vicini allo stile di Giovanni Mazzucco, ma non sono direttamente opera del pittore o della sua bottega. E’ il caso della Crocifissione  nell’antica sacrestia di Niella Tanaro; la Madonna col Bambino nel Santuario del Pasco a Villanova Mondovì: sono segni della fortuna di cui gode il linguaggio del pittore."